version: 2
updates:
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Mariamahmed44"
    assignees:
      - "Mariamahmed44"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group related updates
    groups:
      selenium:
        patterns:
          - "org.seleniumhq.selenium:*"
          - "io.github.bonigarcia:webdrivermanager"
      testing:
        patterns:
          - "org.testng:testng"
          - "com.aventstack:extentreports"
      build:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.maven.plugins:*"
    # Ignore specific dependencies if needed
    ignore:
      - dependency-name: "org.seleniumhq.selenium:selenium-java"
        versions: ["4.0.0-alpha*", "4.0.0-beta*"]
      # Ignore patch updates for stable dependencies
      - dependency-name: "org.testng:testng"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "Mariamahmed44"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    groups:
      actions-core:
        patterns:
          - "actions/checkout"
          - "actions/setup-java"
          - "actions/cache"
          - "actions/upload-artifact"
