name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb
        
    - name: Check project structure
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo "=== Looking for testng.xml ==="
        find . -name "testng.xml" -type f || echo "testng.xml not found"
        echo "=== Looking for test classes ==="
        find . -name "*Test.java" -type f | head -10 || echo "No test classes found"
        echo "=== pom.xml content (surefire plugin) ==="
        grep -A 20 "maven-surefire-plugin" pom.xml || echo "No surefire plugin found"
        
    - name: Run tests (bypassing testng.xml)
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 3
        
        # Force Maven to ignore testng.xml and run tests directly
        mvn clean test \
          -Dsurefire.suiteXmlFiles= \
          -DfailIfNoTests=false \
          -Dtest=**/*Test.java
        
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          src/test/java/utils/reports/
          target/surefire-reports/
          target/screenshots/
        retention-days: 7
