name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb
        
    - name: Check project structure
      run: |
        echo "Checking project files..."
        ls -la
        echo "Looking for testng.xml..."
        find . -name "testng.xml" -type f || echo "testng.xml not found"
        echo "Looking for test classes..."
        find . -name "*Test.java" -type f | head -5 || echo "No test classes found"
        
    - name: Run tests
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 3
        
        # Check if testng.xml exists, if not run tests directly
        if [ -f "testng.xml" ]; then
          echo "Using testng.xml configuration"
          mvn clean test
        else
          echo "No testng.xml found, running tests directly"
          # Run tests without testng.xml - let Maven discover test classes
          mvn clean test -DskipTests=false
        fi
        
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          src/test/java/utils/reports/
          target/surefire-reports/
        retention-days: 7
