name: Manual Test Run

on:
  workflow_dispatch:
    inputs:
      test_class:
        description: 'Test class to run (leave empty for all tests)'
        required: false
      browser:
        description: 'Browser'
        required: false
        default: 'chrome'
        type: choice
        options:
        - chrome
        - firefox

jobs:
  manual-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install browsers
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable firefox xvfb
        
    - name: Run tests
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 3
        
        if [ -n "${{ github.event.inputs.test_class }}" ]; then
          mvn test -Dtest=${{ github.event.inputs.test_class }}
        else
          mvn test
        fi
        
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: manual-test-results
        path: |
          src/test/java/utils/reports/
          target/surefire-reports/
          target/screenshots/
        retention-days: 7
