name: Java TestNG Automation
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          target
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Verify testing.xml exists
      run: |
        if [ -f "testing.xml" ]; then
          echo "testing.xml found"
          cat testing.xml
        else
          echo "testing.xml not found in root directory"
          find . -name "testing.xml" -type f
        fi
        
    - name: Run tests with Maven
      run:  mvn clean test -X

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          target/surefire-reports
          src/test/java/utils/reports/
        if-no-files-found: warn
