name: Java TestNG Automation

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated from v2 to v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4  # Updated from v1 to v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Cache Maven packages
      uses: actions/cache@v4  # Updated from v2 to v4
      with:
        path: |
          ~/.m2/repository
          target
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
        
    - name: Run tests with Maven
      run: mvn clean test
      
    - name: Archive test reports
      uses: actions/upload-artifact@v4  # Updated from v2 to v4
      with:
        name: test-reports
        path: |
          target/surefire-reports
          src/test/java/utils/reports/
        if-no-files-found: warn
